//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSEServiceClient
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://bsestarmfdemo.bseindia.com/2016/01/", ConfigurationName="BSEServiceClient.IMFUploadService")]
    public interface IMFUploadService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bsestarmfdemo.bseindia.com/2016/01/IMFUploadService/getPassword", ReplyAction="http://bsestarmfdemo.bseindia.com/2016/01/IMFUploadService/getPasswordResponse")]
        System.Threading.Tasks.Task<string> getPasswordAsync(string UserId, string MemberId, string Password, string PassKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bsestarmfdemo.bseindia.com/2016/01/IMFUploadService/MFAPI", ReplyAction="http://bsestarmfdemo.bseindia.com/2016/01/IMFUploadService/MFAPIResponse")]
        System.Threading.Tasks.Task<string> MFAPIAsync(string Flag, string UserId, string EncryptedPassword, string param);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IMFUploadServiceChannel : BSEServiceClient.IMFUploadService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class MFUploadServiceClient : System.ServiceModel.ClientBase<BSEServiceClient.IMFUploadService>, BSEServiceClient.IMFUploadService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MFUploadServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(MFUploadServiceClient.GetBindingForEndpoint(endpointConfiguration), MFUploadServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MFUploadServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MFUploadServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MFUploadServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MFUploadServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MFUploadServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> getPasswordAsync(string UserId, string MemberId, string Password, string PassKey)
        {
            return base.Channel.getPasswordAsync(UserId, MemberId, Password, PassKey);
        }
        
        public System.Threading.Tasks.Task<string> MFAPIAsync(string Flag, string UserId, string EncryptedPassword, string param)
        {
            return base.Channel.MFAPIAsync(Flag, UserId, EncryptedPassword, param);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_IMFUploadService))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_IMFUploadService1))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_IMFUploadService))
            {
                return new System.ServiceModel.EndpointAddress("http://pbustarmfsrv113.bseltd.domain:81/MFUploadService/MFUploadService.svc/Basic" +
                        "");
            }
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_IMFUploadService1))
            {
                return new System.ServiceModel.EndpointAddress("https://bsestarmfdemo.bseindia.com/MFUploadService/MFUploadService.svc/Secure");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WSHttpBinding_IMFUploadService,
            
            WSHttpBinding_IMFUploadService1,
        }
    }
}
